In [1]:
import pandas as pd
import numpy as np
# import re
import matplotlib.pyplot as plt

In [37]:
import seaborn as sns

In [2]:
df = pd.read_csv("synthetic-lux-pop-dataset-100000.csv")
df = df.copy()

In [3]:
df

,Unnamed: 0,Gender,Age,Date_of_birth,Nationality,Municipality,Canton,Salary,Social_matricule,Ethnicity,hair_color,hair_lenght,First_name,Surname
0,0,M,31,19920609,Portugal,Luxembourg,Canton Luxembourg,1460.0,199206097835*,white,red,long,Cristiano,Fernandes
1,1,M,41,19821205,Luxembourg,Esch-sur-Alzette,Canton Esch,5303.0,198212053419*,white,gray,medium,Franck,Berthelot
2,2,M,30,19930327,Poland,Luxembourg,Canton Luxembourg,4960.0,199303273513*,white,red,medium,Kornel,Pastuła
3,3,M,63,19600620,Luxembourg,Luxembourg,Canton Luxembourg,4960.0,196006201120*,white,gray,long,Joseph,Verdier
4,4,M,21,20020813,France,Käerjeng,Canton Capellen,4141.0,200208139103*,white,black,medium,Adrien,Lelièvre
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99995,F,73,19500909,Luxembourg,Beaufort,Canton Echternach,0.0,195009090200*,white,gray,medium,Annick,Gaudin
99996,99996,M,87,19360117,Luxembourg,Differdange,Canton Esch,0.0,193601173851*,white,gray,short,Thibaut,Van Acker
99997,99997,F,36,19871016,Ireland,Echternach,Canton Echternach,2223.0,198710168768*,white,brown,long,Brogan,Hedderman
99998,99998,F,33,19900516,Luxembourg,Bissen,Canton Mersch,4055.0,199005169301*,white,red,medium,Louise,Neveu
99999,99999,F,70,19530602,Luxembourg,Weiler-la-Tour,Canton Luxembourg,0.0,195306024949*,white,gray,medium,Mieke,Albert

In [4]:
data = df.drop(["Date_of_birth", "Social_matricule", "hair_color", "hair_lenght", "First_name", "Unnamed: 0"], axis=1)

In [5]:
data

,Gender,Age,Nationality,Municipality,Canton,Salary,Ethnicity,Surname
0,M,31,Portugal,Luxembourg,Canton Luxembourg,1460.0,white,Fernandes
1,M,41,Luxembourg,Esch-sur-Alzette,Canton Esch,5303.0,white,Berthelot
2,M,30,Poland,Luxembourg,Canton Luxembourg,4960.0,white,Pastuła
3,M,63,Luxembourg,Luxembourg,Canton Luxembourg,4960.0,white,Verdier
4,M,21,France,Käerjeng,Canton Capellen,4141.0,white,Lelièvre
...,...,...,...,...,...,...,...,...
99995,F,73,Luxembourg,Beaufort,Canton Echternach,0.0,white,Gaudin
99996,M,87,Luxembourg,Differdange,Canton Esch,0.0,white,Van Acker
99997,F,36,Ireland,Echternach,Canton Echternach,2223.0,white,Hedderman
99998,F,33,Luxembourg,Bissen,Canton Mersch,4055.0,white,Neveu
99999,F,70,Luxembourg,Weiler-la-Tour,Canton Luxembourg,0.0,white,Albert

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 8 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Gender        100000 non-null  object
 1   Age           100000 non-null  int64
 2   Nationality   100000 non-null  object
 3   Municipality  100000 non-null  object
 4   Canton        100000 non-null  object
 5   Salary        100000 non-null  object
 6   Ethnicity     100000 non-null  object
 7   Surname       100000 non-null  object
dtypes: int64(1), object(7)
memory usage: 6.1+ MB

In [7]:
data.columns

Index(['Gender', 'Age', 'Nationality', 'Municipality', 'Canton', 'Salary',
       'Ethnicity', 'Surname'],
      dtype='object')

In [8]:
unique_cantons = data['Canton'].nunique()
unique_cantons
unique_cantons_names = data['Canton'].unique()
unique_cantons_names

array(['Canton Luxembourg', 'Canton Esch', 'Canton Capellen',
       'Canton Clervaux', 'Canton Remich', 'Canton Wiltz',
       'Canton Grevenmacher', 'Canton Diekirch', 'Canton Mersch',
       'Canton Redange', 'Canton Echternach', 'Canton Vianden'],
      dtype=object)

In [9]:
unique_municipalities = data['Municipality'].nunique()
unique_mun_names = data['Municipality'].unique()
#unique_municipalities
unique_mun_names

array(['Luxembourg', 'Esch-sur-Alzette', 'Käerjeng', 'Habscht', 'Sanem',
       'Parc Hosingen', 'Mondorf-les-Bains', 'Wiltz', 'Koerich',
       'Steinsel', 'Hesperange', 'Kayl', 'Junglinster', 'Schifflange',
       "Vallée de l'Ernz", 'Troisvierges', 'Mondercange', 'Wincrange',
       'Walferdange', 'Lorentzweiler', 'Rumelange', 'Mamer',
       'Grevenmacher', 'Dudelange', 'Garnich', 'Erpeldange-sur-Sûre',
       'Feulen', 'Redange-sur-Attert', 'Berdorf', 'Bissen', 'Ettelbruck',
       'Steinfort', 'Frisange', 'Beckerich', 'Roeser', 'Lintgen',
       'Differdange', 'Ell', 'Pétange', 'Echternach', 'Rambrouch',
       'Boulaide', 'Diekirch', 'Helperknapp', 'Esch-sur-Sûre', 'Betzdorf',
       'Mertzig', 'Schuttrange', 'Kehlen', 'Dalheim', 'Wormeldange',
       'Reckange-sur-Mess', 'Niederanven', 'Bertrange', 'Clervaux',
       'Mersch', 'Dippach', 'Strassen', 'Rosport-Mompach', 'Bourscheid',
       'Bettembourg', 'Mertert', 'Bous', 'Biwer', 'Sandweiler',
       'Manternach', 'Useldange', 'Remich', 'Waldbillig',
       'Weiler-la-Tour', 'Kopstal', 'Schieren', 'Consdorf', 'Vianden',
       'Flaxweiler', 'Schengen', 'Heffingen', 'Colmar-Berg', 'Contern',
       'Larochette', 'Beaufort', 'Préizerdaul', 'Goesdorf', 'Leudelange',
       'Lenningen', 'Tandel', 'Lac de la Haute-Sûre', 'Bettendorf',
       'Weiswampach', 'Stadtbredimus', 'Winseler'], dtype=object)

### Importing the dataset with Lat & Lon for cities in Luxembourg

In [10]:
canton_capitals = pd.read_csv("lu.csv")
canton_capitals = canton_capitals.copy()

In [11]:
canton_capitals

,city,lat,lng,country,iso2,admin_name,capital,population,population_proper
0,Luxembourg,49.6117,6.1319,Luxembourg,LU,Luxembourg,primary,132780.0,132780.0
1,Esch-sur-Alzette,49.4969,5.9806,Luxembourg,LU,Esch-sur-Alzette,admin,36228.0,36177.0
2,Dudelange,49.4833,6.0833,Luxembourg,LU,Esch-sur-Alzette,minor,21513.0,21513.0
3,Differdange,49.5222,5.8917,Luxembourg,LU,Esch-sur-Alzette,minor,15455.0,15455.0
4,Belvaux,49.5167,5.9333,Luxembourg,LU,Esch-sur-Alzette,NaN,7826.0,7826.0
...,...,...,...,...,...,...,...,...,...
275,Tandel,49.8970,6.1820,Luxembourg,LU,Vianden,minor,NaN,NaN
276,Esch-sur-Sûre,49.9110,5.9347,Luxembourg,LU,Wiltz,minor,NaN,NaN
277,Mompach,49.7461,6.4650,Luxembourg,LU,Echternach,minor,NaN,NaN
278,Winseler,49.9678,5.8903,Luxembourg,LU,Wiltz,minor,NaN,NaN
279,Boulaide,49.8867,5.8144,Luxembourg,LU,Wiltz,minor,NaN,NaN

In [12]:
canton_capitals["admin_name"].unique()

array(['Luxembourg', 'Esch-sur-Alzette', 'Diekirch', 'Capellen',
       'Echternach', 'Wiltz', 'Remich', 'Grevenmacher', 'Vianden',
       'Mersch', 'Clervaux', 'Redange'], dtype=object)

In [13]:
canton_capitals["city"].unique()

array(['Luxembourg', 'Esch-sur-Alzette', 'Dudelange', 'Differdange',
       'Belvaux', 'Rodange', 'Niedercorn', 'Diekirch', 'Soleuvre',
       'Bascharage', 'Echternach', 'Kayl', 'Steinfort', 'Rumelange',
       'Wiltz', 'Mondorf-les-Bains', 'Grevenmacher', 'Frisange',
       'Obercorn', 'Béreldange', 'Tétange', 'Remich', 'Sandweiler',
       'Junglinster', 'Wasserbillig', 'Bridel', 'Lamadelaine',
       'Helmsange', 'Hesperange', 'Fentange', 'Itzig', 'Alzingen',
       'Vianden', 'Rollingen', 'Eischen', 'Schieren', 'Roodt-sur-Syre',
       'Capellen', 'Clemency', 'Heisdorf', 'Hautcharage', 'Hobscheid',
       'Gonderange', 'Larochette', 'Aspelt', 'Dalheim', 'Canach',
       'Schouweiler', 'Contern', 'Mertert', 'Crauthem', 'Bergem',
       'Clervaux', 'Warken', 'Berdorf', 'Medernach', 'Moutfort',
       'Weiswampach', 'Olm', 'Tuntange', 'Berchem', 'Koerich',
       'Bettendorf', 'Bettange-sur-Mess', 'Garnich', 'Heffingen',
       'Müllendorf', 'Hosingen', 'Pontpierre', 'Nospelt',
       'Kleinbettingen', 'Weiler-la-Tour', 'Gilsdorf', 'Beringen',
       'Noertzange', 'Dippach', 'Berbourg', 'Reckange', 'Grosbous',
       'Ehlerange', 'Bivange', 'Greiveldange', 'Mensdorf', 'Eschdorf',
       'Ehnen', 'Perlé', 'Elvange', 'Oetrange', 'Hellange', 'Rosport',
       'Beckerich', 'Rameldange', 'Reisdorf', 'Schrassig', 'Peppange',
       'Christnach', 'Keispelt', 'Altwies', 'Bourglinster', 'Ingeldorf',
       'Bofferdange', 'Marnach', 'Oberanven', 'Remerschen', 'Münsbach',
       'Helmdange', 'Syren', 'Senningen', 'Huncherange', 'Weidingen',
       'Cruchten', 'Goeblange', 'Bech-Kleinmacher', 'Wellenstein',
       'Gosseldange', 'Erpeldange', 'Hassel', 'Oberfeulen', 'Steinheim',
       'Heiderscheid', 'Heinerscheid', 'Linger', 'Holzem', 'Godbrange',
       'Noerdange', 'Bastendorf', 'Flaxweiler', 'Bigonville', 'Harlange',
       'Sprinckange', 'Burden', 'Pratz', 'Everlange', 'Foetz', 'Machtum',
       'Hunsdorf', 'Rambrouch', 'Platen', 'Blaschette', 'Ell',
       'Scheidgen', 'Ernzen', 'Olingen', 'Stegen', 'Filsdorf',
       'Wolwelange', 'Dahlem', 'Moestroff', 'Buschdorf', 'Eselborn',
       'Gostingen', 'Wintrange', 'Angelsberg', 'Wahlhausen', 'Hoscheid',
       'Bourscheid', 'Osweiler', 'Baschleiden', 'Huldange', 'Nocher',
       'Ermsdorf', 'Niederdonven', 'Niederpallen', 'Schwebsange', 'Bech',
       'Asselborn', 'Oberpallen', 'Doncols', 'Hostert', 'Fingig',
       'Moersdorf', 'Haller', 'Folschette', 'Fouhren', 'Bettborn',
       'Ospern', 'Hollenfels', 'Beyren', 'Boxhorn', 'Schrondweiler',
       'Born', 'Arsdorf', 'Eschweiler', 'Ernster', 'Hovelange',
       'Fennange', 'Fischbach', 'Moesdorf', 'Nothum', 'Livange',
       'Septfontaines', 'Tarchamps', 'Dahl', 'Trintange', 'Reuland',
       'Wormeldange', 'Wilwerdange', 'Schoos', 'Meispelt', 'Roedgen',
       'Berg', 'Hoffelt', 'Brandenbourg', 'Michelau', 'Lieler',
       'Colpach-Haut', 'Kahler', 'Imbringen', 'Kaundorf', 'Lipperscheid',
       'Gœsdorf', 'Holzthum', 'Consthum', 'Altrier', 'Pintsch',
       'Boevange', 'Grevels', 'Kockelscheuer', 'Hoscheiderdickt', 'Surré',
       'Wilwerwiltz', 'Merscheid', 'Nagem', 'Brachtenbach', 'Gralingen',
       'Binsfeld', 'Wincrange', 'Bavigne', 'Putscheid', 'Biwer', 'Mersch',
       'Redange-sur-Attert', 'Pétange', 'Schifflange', 'Walferdange',
       'Strassen', 'Sanem', 'Ettelbruck', 'Bettembourg', 'Bertrange',
       'Kopstal', 'Mamer', 'Mondercange', 'Beaufort', 'Schuttrange',
       'Roeser', 'Steinsel', 'Stadtbredimus', 'Lorentzweiler', 'Lintgen',
       'Kehlen', 'Colmar-Berg', 'Bous', 'Leudelange', 'Betzdorf',
       'Mertzig', 'Schengen', 'Bissen', 'Niederanven',
       'Reckange-sur-Mess', 'Lenningen', 'Boevange-sur-Attert',
       'Useldange', 'Vichten', 'Consdorf', 'Troisvierges', 'Manternach',
       'Niederfeulen', 'Nommern', 'Saeul', 'Waldbredimus', 'Waldbillig',
       'Wahl', 'Tandel', 'Esch-sur-Sûre', 'Mompach', 'Winseler',
       'Boulaide'], dtype=object)

In [14]:
# Mapping from city to lat and lon
city_to_lat = canton_capitals.set_index('city')['lat'].to_dict()
city_to_lon = canton_capitals.set_index('city')['lng'].to_dict()

In [15]:
# Map lat and lon to each admin_name based on city
canton_capitals['admin_lat'] = canton_capitals['admin_name'].map(city_to_lat)
canton_capitals['admin_lon'] = canton_capitals['admin_name'].map(city_to_lon)

# Display the updated DataFrame
canton_capitals

,city,lat,lng,country,iso2,admin_name,capital,population,population_proper,admin_lat,admin_lon
0,Luxembourg,49.6117,6.1319,Luxembourg,LU,Luxembourg,primary,132780.0,132780.0,49.6117,6.1319
1,Esch-sur-Alzette,49.4969,5.9806,Luxembourg,LU,Esch-sur-Alzette,admin,36228.0,36177.0,49.4969,5.9806
2,Dudelange,49.4833,6.0833,Luxembourg,LU,Esch-sur-Alzette,minor,21513.0,21513.0,49.4969,5.9806
3,Differdange,49.5222,5.8917,Luxembourg,LU,Esch-sur-Alzette,minor,15455.0,15455.0,49.4969,5.9806
4,Belvaux,49.5167,5.9333,Luxembourg,LU,Esch-sur-Alzette,NaN,7826.0,7826.0,49.4969,5.9806
...,...,...,...,...,...,...,...,...,...,...,...
275,Tandel,49.8970,6.1820,Luxembourg,LU,Vianden,minor,NaN,NaN,49.9336,6.2075
276,Esch-sur-Sûre,49.9110,5.9347,Luxembourg,LU,Wiltz,minor,NaN,NaN,49.9667,5.9333
277,Mompach,49.7461,6.4650,Luxembourg,LU,Echternach,minor,NaN,NaN,49.8117,6.4217
278,Winseler,49.9678,5.8903,Luxembourg,LU,Wiltz,minor,NaN,NaN,49.9667,5.9333
279,Boulaide,49.8867,5.8144,Luxembourg,LU,Wiltz,minor,NaN,NaN,49.9667,5.9333

In [16]:
# Check for NA in 'lat' and 'Lon' columns
na_in_lat = canton_capitals['admin_lat'].isna().any()
na_in_lon = canton_capitals['admin_lon'].isna().any()

# Print the results
print(f"Are there any NA values in the 'lat' column? {na_in_lat}")
print(f"Are there any NA values in the 'Lon' column? {na_in_lon}")

Are there any NA values in the 'lat' column? True
Are there any NA values in the 'Lon' column? True

In [17]:
na_rows = canton_capitals[canton_capitals['admin_lat'].isna() | canton_capitals['admin_lon'].isna()]
na_rows

,city,lat,lng,country,iso2,admin_name,capital,population,population_proper,admin_lat,admin_lon
78,Grosbous,49.8333,5.9667,Luxembourg,LU,Redange,minor,991.0,991.0,NaN,NaN
85,Perlé,49.8167,5.7667,Luxembourg,LU,Redange,NaN,883.0,883.0,NaN,NaN
90,Beckerich,49.7306,5.8833,Luxembourg,LU,Redange,minor,834.0,834.0,NaN,NaN
124,Noerdange,49.7500,5.9333,Luxembourg,LU,Redange,NaN,599.0,599.0,NaN,NaN
127,Bigonville,49.8500,5.8000,Luxembourg,LU,Redange,NaN,546.0,546.0,NaN,NaN
131,Pratz,49.8000,5.9333,Luxembourg,LU,Redange,NaN,533.0,533.0,NaN,NaN
132,Everlange,49.7667,5.9500,Luxembourg,LU,Redange,NaN,533.0,533.0,NaN,NaN
136,Rambrouch,49.8299,5.8498,Luxembourg,LU,Redange,minor,528.0,528.0,NaN,NaN
137,Platen,49.7833,5.9333,Luxembourg,LU,Redange,NaN,521.0,521.0,NaN,NaN
139,Ell,49.7667,5.8500,Luxembourg,LU,Redange,minor,515.0,515.0,NaN,NaN
145,Wolwelange,49.8286,5.7647,Luxembourg,LU,Redange,NaN,503.0,503.0,NaN,NaN
163,Niederpallen,49.7500,5.9167,Luxembourg,LU,Redange,NaN,438.0,438.0,NaN,NaN
167,Oberpallen,49.7333,5.8500,Luxembourg,LU,Redange,NaN,423.0,423.0,NaN,NaN
169,Hostert,49.8087,5.8659,Luxembourg,LU,Redange,NaN,418.0,418.0,NaN,NaN
173,Folschette,49.8167,5.8667,Luxembourg,LU,Redange,NaN,414.0,414.0,NaN,NaN
175,Bettborn,49.8000,5.9333,Luxembourg,LU,Redange,minor,406.0,406.0,NaN,NaN
176,Ospern,49.7833,5.9000,Luxembourg,LU,Redange,NaN,405.0,405.0,NaN,NaN
182,Arsdorf,49.8667,5.8500,Luxembourg,LU,Redange,NaN,399.0,399.0,NaN,NaN
185,Hovelange,49.7167,5.9000,Luxembourg,LU,Redange,NaN,395.0,395.0,NaN,NaN
206,Colpach-Haut,49.7667,5.8167,Luxembourg,LU,Redange,NaN,324.0,324.0,NaN,NaN
217,Grevels,49.8500,5.9167,Luxembourg,LU,Redange,NaN,282.0,282.0,NaN,NaN
223,Nagem,49.7833,5.8500,Luxembourg,LU,Redange,NaN,263.0,263.0,NaN,NaN
232,Redange-sur-Attert,49.7652,5.8894,Luxembourg,LU,Redange,admin,NaN,NaN,NaN,NaN
264,Useldange,49.7697,5.9822,Luxembourg,LU,Redange,minor,NaN,NaN,NaN,NaN
265,Vichten,49.8031,6.0000,Luxembourg,LU,Redange,minor,NaN,NaN,NaN,NaN
271,Saeul,49.7272,5.9864,Luxembourg,LU,Redange,minor,NaN,NaN,NaN,NaN
274,Wahl,49.8333,5.9000,Luxembourg,LU,Redange,minor,NaN,NaN,NaN,NaN

In [18]:
# Find the lat and Lon for "Redange-sur-Attert"
redange_lat = canton_capitals.loc[canton_capitals['city'] == 'Redange-sur-Attert', 'lat'].iloc[0]
redange_lon = canton_capitals.loc[canton_capitals['city'] == 'Redange-sur-Attert', 'lng'].iloc[0]

# Update the lat and Lon for "Redange"
canton_capitals.loc[canton_capitals['admin_name'] == 'Redange', 'admin_lat'] = redange_lat
canton_capitals.loc[canton_capitals['admin_name'] == 'Redange', 'admin_lon'] = redange_lon

In [19]:
# Check for NA in 'lat' and 'Lon' columns
na_in_lat = canton_capitals['admin_lat'].isna().any()
na_in_lon = canton_capitals['admin_lon'].isna().any()

# Print the results
print(f"Are there any NA values in the 'lat' column? {na_in_lat}")
print(f"Are there any NA values in the 'Lon' column? {na_in_lon}")

Are there any NA values in the 'lat' column? False
Are there any NA values in the 'Lon' column? False

In [21]:
canton_capitals['admin_name'].unique()

array(['Luxembourg', 'Esch-sur-Alzette', 'Diekirch', 'Capellen',
       'Echternach', 'Wiltz', 'Remich', 'Grevenmacher', 'Vianden',
       'Mersch', 'Clervaux', 'Redange'], dtype=object)

In [23]:
canton_capitals['admin_name'] = canton_capitals['admin_name'].str.replace('-sur-Alzette', '')

In [24]:
canton_capitals['admin_name'].unique()

array(['Luxembourg', 'Esch', 'Diekirch', 'Capellen', 'Echternach',
       'Wiltz', 'Remich', 'Grevenmacher', 'Vianden', 'Mersch', 'Clervaux',
       'Redange'], dtype=object)

### Coming back to the synthetic data

In [25]:
data

,Gender,Age,Nationality,Municipality,Canton,Salary,Ethnicity,Surname
0,M,31,Portugal,Luxembourg,Canton Luxembourg,1460.0,white,Fernandes
1,M,41,Luxembourg,Esch-sur-Alzette,Canton Esch,5303.0,white,Berthelot
2,M,30,Poland,Luxembourg,Canton Luxembourg,4960.0,white,Pastuła
3,M,63,Luxembourg,Luxembourg,Canton Luxembourg,4960.0,white,Verdier
4,M,21,France,Käerjeng,Canton Capellen,4141.0,white,Lelièvre
...,...,...,...,...,...,...,...,...
99995,F,73,Luxembourg,Beaufort,Canton Echternach,0.0,white,Gaudin
99996,M,87,Luxembourg,Differdange,Canton Esch,0.0,white,Van Acker
99997,F,36,Ireland,Echternach,Canton Echternach,2223.0,white,Hedderman
99998,F,33,Luxembourg,Bissen,Canton Mersch,4055.0,white,Neveu
99999,F,70,Luxembourg,Weiler-la-Tour,Canton Luxembourg,0.0,white,Albert

In [26]:
data['admin_name'] = data["Canton"].str.replace('Canton ', '')

In [27]:
data

,Gender,Age,Nationality,Municipality,Canton,Salary,Ethnicity,Surname,admin_name
0,M,31,Portugal,Luxembourg,Canton Luxembourg,1460.0,white,Fernandes,Luxembourg
1,M,41,Luxembourg,Esch-sur-Alzette,Canton Esch,5303.0,white,Berthelot,Esch
2,M,30,Poland,Luxembourg,Canton Luxembourg,4960.0,white,Pastuła,Luxembourg
3,M,63,Luxembourg,Luxembourg,Canton Luxembourg,4960.0,white,Verdier,Luxembourg
4,M,21,France,Käerjeng,Canton Capellen,4141.0,white,Lelièvre,Capellen
...,...,...,...,...,...,...,...,...,...
99995,F,73,Luxembourg,Beaufort,Canton Echternach,0.0,white,Gaudin,Echternach
99996,M,87,Luxembourg,Differdange,Canton Esch,0.0,white,Van Acker,Esch
99997,F,36,Ireland,Echternach,Canton Echternach,2223.0,white,Hedderman,Echternach
99998,F,33,Luxembourg,Bissen,Canton Mersch,4055.0,white,Neveu,Mersch
99999,F,70,Luxembourg,Weiler-la-Tour,Canton Luxembourg,0.0,white,Albert,Luxembourg

In [28]:
# Merge the DataFrames on 'admin_name'
data = data.merge(canton_capitals[['admin_name', 'admin_lat', 'admin_lon']], on='admin_name', how='left')

In [35]:
data

,Gender,Age,Nationality,Municipality,Canton,Salary,Ethnicity,Surname,admin_name,admin_lat,admin_lon
0,M,31,Portugal,Luxembourg,Canton Luxembourg,1460.0,white,Fernandes,Luxembourg,49.6117,6.1319
1,M,31,Portugal,Luxembourg,Canton Luxembourg,1460.0,white,Fernandes,Luxembourg,49.6117,6.1319
2,M,31,Portugal,Luxembourg,Canton Luxembourg,1460.0,white,Fernandes,Luxembourg,49.6117,6.1319
3,M,31,Portugal,Luxembourg,Canton Luxembourg,1460.0,white,Fernandes,Luxembourg,49.6117,6.1319
4,M,31,Portugal,Luxembourg,Canton Luxembourg,1460.0,white,Fernandes,Luxembourg,49.6117,6.1319
...,...,...,...,...,...,...,...,...,...,...,...
2898357,F,70,Luxembourg,Weiler-la-Tour,Canton Luxembourg,0.0,white,Albert,Luxembourg,49.6117,6.1319
2898358,F,70,Luxembourg,Weiler-la-Tour,Canton Luxembourg,0.0,white,Albert,Luxembourg,49.6117,6.1319
2898359,F,70,Luxembourg,Weiler-la-Tour,Canton Luxembourg,0.0,white,Albert,Luxembourg,49.6117,6.1319
2898360,F,70,Luxembourg,Weiler-la-Tour,Canton Luxembourg,0.0,white,Albert,Luxembourg,49.6117,6.1319
2898361,F,70,Luxembourg,Weiler-la-Tour,Canton Luxembourg,0.0,white,Albert,Luxembourg,49.6117,6.1319

### Exporting

In [36]:
data.to_csv('exported.csv', index=False)

In [ ]:
# Assuming 'Age' and 'Canton' are column names
aging_population = df[df['Age'] > 65].groupby('Canton').size() / df.groupby('Canton').size()
aging_population.sort_values(ascending=False, inplace=True)
plt.figure(figsize=(10, 6))
aging_population.plot(kind='bar')
plt.title('Percentage of Aging Population by Canton')
plt.ylabel('Percentage')
plt.xlabel('Canton')
plt.show()

# 2. Average salary for each canton
# Assuming 'Salary' and 'Canton' are column names
average_salary = df.groupby('Canton')['Salary'].mean()
plt.figure(figsize=(10, 6))
average_salary.plot(kind='bar', color='skyblue')
plt.title('Average Salary by Canton')
plt.ylabel('Average Salary')
plt.xlabel('Canton')
plt.show()

# 3. Difference in income between men and women
# Assuming 'Salary', 'Gender' are column names
gender_income = df.groupby('Gender')['Salary'].mean()
plt.figure(figsize=(7, 5))
gender_income.plot(kind='bar', color=['pink', 'lightblue'])
plt.title('Average Income by Gender')
plt.ylabel('Average Income')
plt.xticks(rotation=0)
plt.show()

# 4. Cantons with the highest proportion of foreign citizenship
# Assuming 'Citizenship' and 'Canton' are column names, and 'Luxembourgish' is a value
foreign_citizenship = df[df['Citizenship'] != 'Luxembourgish'].groupby('Canton').size() / df.groupby('Canton').size()
foreign_citizenship.sort_values(ascending=False, inplace=True)
plt.figure(figsize=(10, 6))
foreign_citizenship.plot(kind='bar', color='green')
plt.title('Proportion of Foreign Citizenship by Canton')
plt.ylabel('Proportion')
plt.xlabel('Canton')
plt.show()

### Visualizations

# other

### Scraping the dataset with cantons and their capitals

In [12]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [13]:
url = 'https://en.wikipedia.org/wiki/Cantons_of_Luxembourg'

In [14]:
response = requests.get(url)
response

In [15]:
soup = BeautifulSoup(response.content, 'html.parser')

In [16]:
#soup

In [17]:
indiatable=soup.find('table', {'class':"wikitable sortable"})

In [18]:
#indiatable

In [19]:
cantons=pd.read_html(str(indiatable))
# convert list to dataframe
df_cantons=pd.DataFrame(cantons[0])
df_cantons

,Name,Luxembourgish name,Capital,Electoral district,Coat of arms[1]
0,Clervaux,Klierf,Clervaux,North,NaN
1,Wiltz,Wolz,Wiltz,North,NaN
2,Vianden,Veianen,Vianden,North,NaN
3,Redange,Réiden,Redange,North,NaN
4,Diekirch,Dikrech,Diekirch,North,NaN
5,Mersch,Miersch,Mersch,Centre,NaN
6,Echternach,Iechternach,Echternach,East,NaN
7,Capellen,Kapellen,Mamer,South,NaN
8,Luxembourg,Lëtzebuerg,Luxembourg City,Centre,NaN
9,Grevenmacher,Gréiwemaacher,Grevenmacher,East,NaN
10,Esch-sur-Alzette,Esch-Uelzecht,Esch-sur-Alzette,South,NaN
11,Remich,Réimech,Remich,East,NaN

### Updating the synthetic dataframe